### ISSUE TITLE
python: fails to detect curses library

### ISSUE THREAD

**Issue by dellelce** [dellelce/mkit#8]
The ```python``` profile fails to detect the ```curses``` library because of the default install uses a sub-directory while python source expects the ```curses.h``` header to be in the includes directory.

**Comment by dellelce** [comment]
This issue is still there.

**Comment by dellelce** [comment]
as of current version (3.12.1) the issue is still there:
```python
>>> import curses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/python/lib/python3.12/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by dellelce** [comment]
as of one of the latest version `3.13.1` the issue appears to have been solved, but there was no change on `mkit`'s side.
```python
[antonio 1257 @antolap3 WSL daily]$  /app/shared/default/bin/python3
Python 3.13.1 (main, Jan 22 2025, 20:55:26) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _curses
>>> _curses.ncurses_version
curses.ncurses_version(major=6, minor=5, patch=20240427)
>>> _curses.version
b'2.2'
```

Will leave open for now.
